#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int autonProgram = 1;//tracker for which auton program to run
int park = 0; //variable for selecting to park in auton
int defense = 0;

	// Leave this value alone; counting starts at 1
	int lcdScreenMin = 1;

	//  IMPORTANT!!!
	// Total # menu items ***** Note Adjust this to match your number of programs!!!
	int lcdScreenMax = 17;

	// Counter for what to display on the screen
	int lcdScreen = 1;

	//Turns on the Backlight
	bLCDBacklight = true;

	// Leave these values alone
	// In RobotC:
	// when the left button is pressed, nLCDButtons = 1
	// when middle button is pressed, nLCDButtons = 2
	// when right button is pressed, nLCDButtons = 4
	const short leftButton = 1;
	const short centerButton = 2;
	const short rightButton = 4;
while (1==1)
{
			// left button
		if (nLCDButtons == leftButton) {
			if (lcdScreenMin == lcdScreen) {
				lcdScreen = lcdScreenMax;
				wait1Msec(250);
			}
			else {
				lcdScreen= lcdScreen-1;
				wait1Msec(250);
			}
		}

		// right button
		if (nLCDButtons == rightButton) {
			if (lcdScreenMax == lcdScreen) {
				lcdScreen = lcdScreenMin;
				wait1Msec(250);
			}
			else {
				lcdScreen=lcdScreen+1;
				wait1Msec(250);
			}
		}

		// The rest of pre-auton checks to see whether the middle
		// button is pressed

		// Each menu item below has 2 blocks of code, depending on
		// whether you've already selected this option, or not

		// If you have not already selected this option as
		// your choice, it will display the text normally, and will
		// then check to see if you're pressing the middle button.

		//------------------------------------------------------------//
		if (lcdScreen == 1 && autonProgram != 1) {
			displayLCDCenteredString (0, "auton 1");
			displayLCDCenteredString (1, "red_Near");

			// When you press the middle button, the screen says,
			// ?Blah blah has / been selected!? for 1.5 seconds
			// and also sets the autonProgram variable
			if (nLCDButtons == centerButton) {
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "red_Near");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		// If you have already selected this item, the menu
		// text will have [square brackets] around it
		// to indicate that this is the option you?ve chosen.
		else if (lcdScreen == 1 && autonProgram == 1) {
			displayLCDCenteredString (0, "[auton 1]");
			displayLCDCenteredString (1, "[red_Near]");
		}
		//------------------------------------------------------------//
		else if (lcdScreen == 2 && autonProgram != 2) {
			displayLCDCenteredString (0, "auton 2");
			displayLCDCenteredString (1, "red_Near w-PARK");

			if (nLCDButtons == centerButton) {
				autonProgram = lcdScreen;
				park = 1;
				displayLCDCenteredString (0, "red_Near w-PARK");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 2 && autonProgram == 2) {
			displayLCDCenteredString (0, "[auton 2]");
			displayLCDCenteredString (1, "[red_Near w-PARK]");
		}
		//------------------------------------------------------------//
		else if (lcdScreen == 3 && autonProgram != 3)
		{
			displayLCDCenteredString (0, "auton 3");
			displayLCDCenteredString (1, "blue_Near");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "blue_Near");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 3 && autonProgram == 3) {
			displayLCDCenteredString (0, "[auton 3]");
			displayLCDCenteredString (1, "[blue_Near]");
		}
		//------------------------------------------------------------//
		else if (lcdScreen == 4 && autonProgram != 4) {
			displayLCDCenteredString (0, "auton 4");
			displayLCDCenteredString (1, "blue_Near w-PARK");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 1;
				displayLCDCenteredString (0, "blue_Near w-PARK");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 4 && autonProgram == 4)
		{
			displayLCDCenteredString (0, "[auton 4]");
			displayLCDCenteredString (1, "[blue_Near w-PARK]");
		}
		//-------------------------------------------------------------//
		else if (lcdScreen == 5 && autonProgram != 5)
		{
			displayLCDCenteredString (0,"auton 5");
			displayLCDCenteredString (1, "red_Far");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "red_Far");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 5 && autonProgram == 5) {
			displayLCDCenteredString (0, "[auton 5]");
			displayLCDCenteredString (1, "[red_Far]");

		}
		//---------------------------------------------------------------//
		else if (lcdScreen == 6 && autonProgram != 6)
		{
			displayLCDCenteredString (0,"auton 6");
			displayLCDCenteredString (1, "red_Far w-PARK");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 1;
				displayLCDCenteredString (0, "red_Far w-PARK");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 6 && autonProgram == 6) {
			displayLCDCenteredString (0, "[auton 6]");
			displayLCDCenteredString (1, "[red_Far w-PARK]");

		}
		//------------------------------------------------------------------//
		else if (lcdScreen == 7 && autonProgram != 7)
		{
			displayLCDCenteredString (0,"auton 7");
			displayLCDCenteredString (1, "blue_Far");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "blue_Far");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 7 && autonProgram == 7) {
			displayLCDCenteredString (0, "[auton 7]");
			displayLCDCenteredString (1, "[blue_Far]");
		}
		//------------------------------------------------------------------//
		else if (lcdScreen == 8 && autonProgram != 8)
		{
			displayLCDCenteredString (0,"auton 8");
			displayLCDCenteredString (1, "blue_Far w-PARK");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 1;
				displayLCDCenteredString (0, "blue_Far w-PARK");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 8 && autonProgram == 8) {
			displayLCDCenteredString (0, "[auton 8]");
			displayLCDCenteredString (1, "[blue_Far w-PARK]");
		}
		//------------------------------------------------------------------//
		else if (lcdScreen == 9 && autonProgram != 9)
		{
			displayLCDCenteredString (0,"auton 9");
			displayLCDCenteredString (1, "Skills Near");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "Skills Near");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 9 && autonProgram == 9) {
			displayLCDCenteredString (0, "[auton 9]");
			displayLCDCenteredString (1, "[Skills Near]");
		}

		//------------------------------------------------------------------//
		else if (lcdScreen == 10 && autonProgram != 10)
		{
			displayLCDCenteredString (0,"auton 10");
			displayLCDCenteredString (1, "Skills Far");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "Skills Far");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 10 && autonProgram == 10) {
			displayLCDCenteredString (0, "[auton 10]");
			displayLCDCenteredString (1, "[Skills Far]");
		}

		//------------------------------------------------------------------//
		else if (lcdScreen == 11 && autonProgram != 11)
		{
			displayLCDCenteredString (0,"auton 11");
			displayLCDCenteredString (1, "Accuracy");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "Accuracy");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 11 && autonProgram == 11) {
			displayLCDCenteredString (0, "[auton 11]");
			displayLCDCenteredString (1, "[Accuracy]");
		}
		//------------------------------------------------------------------//
		else if (lcdScreen == 12 && autonProgram != 12)
		{
			displayLCDCenteredString (0,"auton 12");
			displayLCDCenteredString (1, "NO AUTON");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				displayLCDCenteredString (0, "NO AUTON");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 12 && autonProgram == 12) {
			displayLCDCenteredString (0, "[auton 12");
			displayLCDCenteredString (1, "[NO AUTON]");
		}

		//------------------------------------------------------------------//
		else if (lcdScreen == 13 && autonProgram != 13)
		{
			displayLCDCenteredString (0,"auton 13");
			displayLCDCenteredString (1, "red_far_defense");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				defense = 1;
				displayLCDCenteredString (0, "red_far_defense");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 13 && autonProgram == 13) {
			displayLCDCenteredString (0, "[auton 13]");
			displayLCDCenteredString (1, "[red_far_def]");
		}
		//------------------------------------------------------------------//
		else if (lcdScreen == 14 && autonProgram != 14)
		{
			displayLCDCenteredString (0,"auton 14");
			displayLCDCenteredString (1, "red_far_def w/P");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 1;
				defense = 1;
				displayLCDCenteredString (0, "red_far_def w/P");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 14 && autonProgram == 14) {
			displayLCDCenteredString (0, "[auton 14]");
			displayLCDCenteredString (1, "[red_far_defw/P]");
		}

		//------------------------------------------------------------------//
		else if (lcdScreen == 15 && autonProgram != 15)
		{
			displayLCDCenteredString (0,"auton 15");
			displayLCDCenteredString (1, "blue_far_defense");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 0;
				defense = 1;
				displayLCDCenteredString (0, "blue_far_defense");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 15 && autonProgram == 15) {
			displayLCDCenteredString (0, "[auton 15]");
			displayLCDCenteredString (1, "[blue_far_def]");
		}
		//------------------------------------------------------------------//
		else if (lcdScreen == 16 && autonProgram != 16)
		{
			displayLCDCenteredString (0,"auton 16");
			displayLCDCenteredString (1, "blue_far_def w/P");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				park = 1;
				defense = 1;
				displayLCDCenteredString (0, "blue_far_def w/P");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 16 && autonProgram == 16) {
			displayLCDCenteredString (0, "[auton 16]");
			displayLCDCenteredString (1, "[blue_far_d w/P]");
		}

		//------------------------------------------------------------------//
		else if (lcdScreen == 17 && autonProgram != 17)
		{
			displayLCDCenteredString (0,"auton 17");
			displayLCDCenteredString (1, "Skills_2");

			if (nLCDButtons == centerButton)
			{
				autonProgram = lcdScreen;
				displayLCDCenteredString (0, "Skills_2");
				displayLCDCenteredString (1, "is selected!");
				wait1Msec(1500);
			}
		}

		else if (lcdScreen == 17 && autonProgram == 17) {
			displayLCDCenteredString (0, "[auton 17]");
			displayLCDCenteredString (1, "[Skills_2]");
		}


		//------------------------------------------------------------------//
		// this last menu option does not set the autonProgram
		// variable, but rather displays the value of a sensor
		// that is useful for the drive team to see in pre-auton
		//else if (lcdScreen == ? ) {
		//displayLCDCenteredString (0,"Ultrasonic Val");
		//displayLCDNumber(1, 0,SensorValue[myUltrasonic], -1);
		//}

	}	// end of while-disabled loop
}// end of pre-auton

